### ISSUE TITLE
Drupal install freezes

### ISSUE THREAD

**Issue by jaireina** [lcatlett/blt-ddev#4] opened 2020-04-28 15:18 UTC
Hi, thanks for creating this plugin, it's awesome.

It does enable blt to be used on ddev, but for some reason when I run ddev blt setup, it gets to a point where it freezes.

This is what I see when I run it when the -vvv flag:

 [notice] Starting Drupal installation. This takes a while. [39.26 sec, 3.96 MB]
 [debug] Calling install_drupal(Composer\Autoload\ClassLoader, array) [39.28 sec, 4.03 MB]

No errors are triggered after that, it just remains in there.

This is probably not an issue with the plugin, but I just wanted to put the question here in case you your somebody else has had a similar problem.

Thanks,

**Comment by lcatlett** [comment] 2020-04-28 18:42
@jaireina - this is likely a BLT issue and not an issue with this plugin, but could you paste the full output of `ddev blt doctor`? I am wondering if this might be an issue with BLT and drupal core versions (BLT 11 does not have support for Drupal 9 core, while BLT 12 is highly experimental currently), so seeing your full doctor output might help me narrow down the cause.

**Comment by lcatlett** [comment] 2020-06-23 15:21
closing due to no reply

**Closed by lcatlett** 2020-06-23 15:21 UTC
